### PR TITLE
Bump to version 0.9.72 and rework dependencies

### PR DESCRIPTION
**Pull request by t20100**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This PR bumps to version 0.9.72 and update the list of entry points (and associated tests to run).
It also reworks the list of dependencies by resynchronising it with `setuptools`'s `install_requires` and extending it with "optional" dependencies.

### CODE REVIEW

**Comment by t20100** [comment]
@conda-forge-admin, please rerender

**Review by maurov — APPROVED** [review]

**Comment by t20100** [comment]
- Adding `tomopy` as a dependency adds a dependency on `cudatoolkit`, which can put some constraints on installation.
- Adding `py3dmol` as a dependency adds a dependency on the `jupyter` stack.

 So that's maybe not a good idea unless those are really needed.

**Comment by t20100** [comment]
Looking at `tomopy` dependencies, `libtomo` looks to have alternatives with/without CUDA, so it's not a constraint for installation.

**Comment by maurov** [comment]
@t20100 thanks for your great work on the recipe! Here my points of view:
- `xraylarch-base` -> green light with this.
- `xraylarch` -> I would add `jupyter` and `plotly` as explicit dependencies and keep `py3dmol` too. We are using Jupyter notebooks more and more and we have strong requests for it.
- `xraylarch-imaging` or `xraylarch-tomo` -> I would move `tomopy` strong dependency in a  separate package, as there are few users for it (I suppose mostly GSECARS tomography users)

@newville could you express your point of view too?

**Comment by t20100** [comment]
Regarding `tomopy`, since it does not require CUDA it is not a strong constraint.

**Comment by newville** [comment]
@t20100 @maurov +1 on having plotly, jupyter be necessary for the basic xraylarch conda package.  I'm okay with adding to that `py3dmol`  if it is not otherwise a burden. 

I am OK with having wxPython be an optional add-on, or perhaps a `xraylarch-wxguis` package (wxPython, wxmplot).   I think that is not a big additional dependency tree, but it is not zero.

I would suggest not having `tomopy` as a dependency at all, but a `xraylarch-tomopy` package would be OK.  That is,   `tomopy` does seem to be a big additional dependency tree.   And, I believe that the usage is pretty small (and that they are all people using my beamline), and we can definitely say that if you also happen to have `tomopy` installed, then some otherwise optional `xraylarch` functionality turns on.

**Comment by t20100** [comment]
Thanks for the feedback!

How it's done for other packages (e.g., `matplotlib`, `pyFAI`) is to have a `-base` package without the GUI dependencies and the package with the default name has the GUI dependencies (e.g., `pyqt` for `matplotlib`, and `wxpython` and `wx*` packages here).

This is what is proposed in PR #26.

I propose to remove `tomopy` for now, and check how conda-forge deals with "extras" dependency target before adding a `xraylarch-tomopy`.

**Comment by t20100** [comment]
Dependency on `tomopy` removed

**Comment by t20100** [comment]
Following dependency management in xraylarch (see 
https://github.com/xraypy/xraylarch/issues/468#issuecomment-1797163125) I'm closing this PR and reopen a new one for v0.9.73

**Pull request closed without merging**
