### PR TITLE
Update to 0.9.74 update dependencies and split package

### PR DESCRIPTION
**Pull request by t20100**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This PR follows previous PR #26 on splitting the package.
It updates dependencies according to https://github.com/xraypy/xraylarch/blob/master/setup.cfg
It also updates the tested entry points.

### CODE REVIEW

**Comment by t20100** [comment]
@conda-forge-admin, please rerender

**Comment by t20100** [comment]
I removed the `setup.py` patch since it no longer works with recent change from `setup.py` to `setup.cfg` in upstream.
This patch might need to be restored in some way to avoid embedding unused files.

**Comment by t20100** [comment]
CI fails because `pip check` fails due to missing dependencies in `pycifrw`:
```
+ pip check
pycifrw 4.4.6 requires ply, which is not installed.
```

PR https://github.com/conda-forge/pycifrw-feedstock/pull/28 fixes it in pycifrw.

**Comment by t20100** [comment]
Bumped to 0.9.74 and comment `pip check` for now, so CI should pass

**Review by maurov — APPROVED** [review]

**Pull request merged**
